"""
/loom 온보딩 전처리기 — 과거 Claude Code 대화에서 '명시적 지시·반복 요청'만
안전하게 추려 후보 목록을 만든다. SKILL.md(Claude)가 이 JSON 출력을 받아
사용자에게 '근거 + 만들면 이렇게 편해짐(효용)'과 함께 제시하고 승인받는다.

설계 (Codex 적대검증 2026-06-26 반영):
- Claude가 대화 원문을 직접 읽지 않는다 — 토큰 폭발·프라이버시 유출 방지.
  이 스크립트가 먼저 추리고 redact한 '증거 스니펫'만 넘긴다.
- '성격·말투 추측' 안 함(헛것 양산). 사용자가 *명시적으로 말한* 지시만.
- evidence-gated: 후보마다 관측 횟수 + redacted 근거. 1회성은 버린다(최소 2회).
- redaction: 이메일·토큰·절대경로·긴 숫자 마스킹. tool 출력·대용량 붙여넣기 제외.
- 경로·스키마는 안정 계약이 아니다 — 못 찾거나 파싱 실패하면 조용히 건너뛰고,
  히스토리 디렉토리 자체가 없으면 명확히 중단 신호를 낸다.

사용: python3 extract.py [--sessions N] [--min-count M]  → stdout에 JSON
"""
import sys
import os
import re
import json
import glob
import argparse

# 명시적 지시로 볼 만한 한국어/영어 신호어. 보수적으로(노이즈 적게).
INSTRUCTION_CUES = [
    r"항상", r"앞으로", r"무조건", r"반드시", r"꼭",
    r"하지\s?마", r"하지\s?말", r"절대", r"금지",
    r"\b로 (해|써|짜|보여|만들)", r"\b는 .{1,20} *(로|으로) ",
    r"always", r"never", r"do not\b", r"don't\b", r"from now on",
]
CUE_RE = re.compile("|".join(INSTRUCTION_CUES), re.IGNORECASE)

# redaction 패턴 — LLM 보내기 전 마스킹.
# 경로 패턴: 중간 디렉토리명에 공백이 있어도(C:\Users\Alice Wong\...) 잡되,
# 마지막 세그먼트는 공백에서 끊어 뒤따르는 문장(예: "...에 있어")까지 먹지 않게 한다.
REDACTORS = [
    (re.compile(r"[\w.+-]+@[\w-]+\.[\w.-]+"), "<EMAIL>"),
    (re.compile(r"[A-Za-z]:\\(?:[^\\/\r\n\"'<>|?*]+[\\/])*[^\\/\s\r\n\"'<>|?*]+"),
     "<PATH>"),
    (re.compile(r"/(?:home|Users)/(?:[^/\r\n\"'<>|?*]+/)*[^/\s\r\n\"'<>|?*]+"),
     "<PATH>"),
    (re.compile(r"\b[A-Za-z0-9_\-]{24,}\b"), "<TOKEN>"),
    (re.compile(r"\b\d{8,}\b"), "<NUM>"),
]

MAX_SNIPPET = 160          # 근거 스니펫 길이 상한
MAX_LINE_BYTES = 4000      # 이보다 큰 메시지(대용량 붙여넣기)는 통째 제외

# user role로 기록돼도 '사용자 자연 발화'가 아닌 것 — 거른다.
# (슬래시/워크플로 호출, 게이트가 넣은 구조화 프롬프트, 시스템 안내문, 훅 주입)
NOISE_MARKERS = (
    "hook success", "hook feedback",
    "<system-reminder>", "<command-name>", "<command-message>",
    "<command-args>", "<local-command-stdout>", "<local-command-stderr>",
    "local-command-caveat",
    "DO NOT respond to these messages",
    "The messages below were generated by the user while running local commands",
    "Invoke: Workflow", 'Run the "',
)


def warn(msg):
    """파싱·읽기 실패를 조용히 삼키지 않고 stderr에 남긴다(stdout JSON은 안 더럽힘)."""
    print(f"[extract.py] {msg}", file=sys.stderr)


def is_noise(text):
    """훅 주입·슬래시명령·워크플로 호출·구조화(JSON) 프롬프트·문서 조각을 거른다."""
    if any(m in text for m in NOISE_MARKERS):
        return True
    t = text.lstrip()
    if t[:3] in ("## ", "###") or t.startswith("- **") or t.startswith("> "):
        return True          # 마크다운 헤더·목록·인용 = 문서 조각, 발화 아님
    if t.startswith("{") or '{"' in t[:48]:
        return True          # JSON/구조화 덩어리(proposal·tool 입력 등)
    return False


def redact(text):
    for pat, repl in REDACTORS:
        text = pat.sub(repl, text)
    return text


def find_history_dir():
    """~/.claude/projects 위치. 없으면 None(스킬이 중단 안내하게)."""
    base = os.path.join(os.path.expanduser("~"), ".claude", "projects")
    return base if os.path.isdir(base) else None


def recent_session_files(hist_dir, n):
    files = glob.glob(os.path.join(hist_dir, "**", "*.jsonl"), recursive=True)
    files.sort(key=lambda p: os.path.getmtime(p), reverse=True)
    return files[:n]


def iter_user_texts(path):
    """한 세션 파일에서 순수 user 텍스트만(스트리밍). tool_result·대용량 제외."""
    parse_errors = 0
    try:
        with open(path, encoding="utf-8") as f:
            for ln in f:
                if len(ln) > MAX_LINE_BYTES:
                    continue
                ln = ln.strip()
                if not ln:
                    continue
                try:
                    rec = json.loads(ln)
                except Exception:
                    parse_errors += 1
                    continue
                msg = rec.get("message", rec)
                role = msg.get("role") or rec.get("type")
                if role != "user":
                    continue
                content = msg.get("content")
                if isinstance(content, str):
                    yield content
                elif isinstance(content, list):
                    # tool_result가 섞인 줄은 통째 건너뜀(사용자 발화 아님)
                    if any(isinstance(b, dict) and b.get("type") == "tool_result"
                           for b in content):
                        continue
                    for b in content:
                        if isinstance(b, dict) and b.get("type") == "text":
                            yield b.get("text", "")
    except Exception as e:
        warn(f"could not read session file {os.path.basename(path)}: {e}")
        return
    if parse_errors:
        warn(f"{os.path.basename(path)}: skipped {parse_errors} line(s) with JSON parse errors")


def split_sentences(text):
    # 줄·문장부호 기준 단순 분리(명시 지시는 보통 한 문장).
    parts = re.split(r"[\n.!?。!?]+", text)
    return [p.strip() for p in parts if p.strip()]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--sessions", type=int, default=40)
    ap.add_argument("--min-count", type=int, default=2)
    args = ap.parse_args()

    hist = find_history_dir()
    if not hist:
        print(json.dumps({"ok": False,
                          "reason": "no_history",
                          "hint": "~/.claude/projects 를 찾지 못했습니다."},
                         ensure_ascii=False))
        return

    files = recent_session_files(hist, args.sessions)
    # 후보 문장 → {정규화키: {count, sessions, samples}}
    cand = {}
    for path in files:
        sid = os.path.basename(path)
        seen_in_session = set()
        for text in iter_user_texts(path):
            if is_noise(text):          # 메시지 통째가 시스템/도구 텍스트면 건너뜀
                continue
            for sent in split_sentences(text):
                if len(sent) > 400 or not CUE_RE.search(sent):
                    continue
                if is_noise(sent):      # 문장 단위로도 한 번 더(섞인 경우)
                    continue
                key = re.sub(r"\s+", " ", sent.lower())[:120]
                if key in seen_in_session:
                    continue
                seen_in_session.add(key)
                slot = cand.setdefault(key, {"count": 0, "sessions": set(),
                                             "samples": []})
                slot["count"] += 1
                slot["sessions"].add(sid)
                if len(slot["samples"]) < 3:
                    snip = redact(sent)[:MAX_SNIPPET]
                    slot["samples"].append(snip)

    # min-count 이상 = 반복 신호만 후보로(1회성 버림)
    out = []
    for key, slot in cand.items():
        if slot["count"] < args.min_count:
            continue
        out.append({
            "observed_count": slot["count"],
            "session_count": len(slot["sessions"]),
            "evidence": slot["samples"],   # 이미 redacted
        })
    out.sort(key=lambda c: c["observed_count"], reverse=True)

    print(json.dumps({
        "ok": True,
        "scanned_sessions": len(files),
        "candidate_count": len(out),
        "candidates": out[:30],
        "note": "이건 '명시 지시' 후보일 뿐이다. Claude가 묶어서 규칙/카드 초안 + "
                "효용설명으로 다듬고, 사용자 승인을 받아야 한다. 성격·말투 추측 금지.",
    }, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
